---
name: "Continuous Integration | main"

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  composite-action-lint:
    name: iac-action-terraform-lint // continuous // composite-action-lint
    runs-on: ubuntu-latest

    steps:
      - name: composite-action-lint // checkout
        uses: actions/checkout@v3

      - name: composite-action-lint // install-action-validator
        run: |
          gh release download --pattern "*_linux_amd64" -R mpalmer/action-validator --skip-existing
          chmod +x ./action-validator_linux_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: composite-action-lint // execute
        run: ./action-validator_linux_amd64 -v action.yml

  test-tflint-versions:
    name: iac-ac-action-terraform-lint // continuous // test-tflint-versions

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['v0.42.0', 'latest']

    runs-on: ${{ matrix.os }}

    steps:
      - name: test-tflint-versions // checkout
        uses: actions/checkout@v3

      - name: test-tflint-versions // execute
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: test-tflint-versions // collect-results
        id: collect-results
        run: echo version=v$(tflint --version | head -n1 | cut -d" " -f3) >> $GITHUB_OUTPUT

      - name: test-tflint-versions // verify-version
        if: ${{ matrix.version != 'latest' }}
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal
          actual   : ${{ steps.collect-results.outputs.version }}
          expected : ${{ matrix.version }}

      - name: test-tflint-versions // collect-facts
        id: collect-facts
        run: echo version=v$(gh release list -R terraform-linters/tflint --exclude-drafts --limit 10 | grep Latest | cut -f1 | cut -dv -f2) >> $GITHUB_OUTPUT
        if: ${{ matrix.version == 'latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test-tflint-versions // verify-latest
        if: ${{ matrix.version == 'latest' }}
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal
          actual   : ${{ steps.collect-results.outputs.version }}
          expected : ${{ steps.collect-facts.outputs.version }}

  test-tflint-fail:
    name: iac-ac-action-terraform-lint // continuous // test-tflint-versions
    runs-on: ubuntu-latest

    steps:
      - name: test-tflint-versions // checkout
        uses: actions/checkout@v3

      - name: test-tflint-versions // execute
        id: execute
        uses: ./
        with:
          terraform-dir: .github/test-harness/fail
        continue-on-error: true

      - name: test-tflint-versions // verify
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal
          actual   : ${{ steps.execute.outcome }}
          expected : failure

  test-tflint-config:
    name: iac-ac-action-terraform-lint // continuous // test-tflint-config
    runs-on: ubuntu-latest

    steps:
      - name: test-tflint-versions // checkout
        uses: actions/checkout@v3

      - name: test-tflint-versions // execute
        id: execute
        uses: ./
        with:
          config: .github/test-harness/config/config.hcl
          terraform-dir: .github/test-harness/config

  test-tflint-vars:
    name: iac-ac-action-terraform-lint // continuous // test-tflint-vars
    runs-on: ubuntu-latest

    steps:
      - name: test-tflint-vars // checkout
        uses: actions/checkout@v3

      - name: test-tflint-vars // execute
        id: execute
        uses: ./
        with:
          terraform-dir: .github/test-harness
          vars: foo=bar,baz=boo

      - name: test-tflint-vars // verify
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal
          actual   : ${{ steps.execute.outputs.vars }}
          expected : "--var='foo=bar' --var='baz=boo'"

